name: 'game_oclock_client'
version: '1.3.7+52'
description: "Game o'Clock client for dart"
homepage: ''
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  retry: ^3.1.2
  collection: ^1.17.2
  intl: ^0.19.0
  meta: ^1.8.0

dev_dependencies:
  test: ^1.22.1
